
export const PRODUCT_CATEGORIES = [
  'Electronics',
  'Clothing',
  'Books',
  'Home & Garden',
  'Sports & Outdoors',
  'Health & Beauty',
  'Automotive',
  'Office Supplies',
  'Food & Beverages',
  'Software & Services',
  'Hardware',
  'Groceries',
  'Furniture',
  'Toys & Games',
  'Tools & Equipment',
  'Beauty & Personal Care',
  'Jewelry & Watches',
  'Music & Movies',
  'Pet Supplies',
  'Industrial & Scientific',
  'Baby Products',
  'Arts & Crafts',
  'Patio, Lawn & Garden',
];
